### ISSUE TITLE
Fast moving, cropping and scaling

### ISSUE THREAD

**Issue by Chessterford** [Xaymar/obs-StreamFX#278]
### Description

Hello! I really like your project, the new features are amazing. But after installing the plugin, the ability to use fast scaling, cropping and moving windows in the OBS disappeared. I know that it is possible to do it in additional parameters, but this is an extremely slow way out of the situation.

In other words, the selection of the source with a frame for interaction has disappeared, this is extremely lacking.

Tell me, is it supposed to be? Perhaps there is a solution or some parameter in the plugin that allows you to use the above functions.

### System Information

- Software Version: [0.8.00]
- Operating System: [Windows]
- Kernel Version: [1903]
- CPU: [AMD Ryzen 5 1600 3.8 GHz]
- GPU: [GTX 1660]
- RAM: [16GB]

**Comment by Xaymar** [comment]
I have never seen the behavior, could you upload a video of it?`The plugin should have no way to make this happen.

**Comment by Xaymar** [comment]
If there's no further reply to this, I will close this in 4 days.

**Comment by skeletonbow** [comment]
This sounds to me like you've disabled features in OBS settings that are now no longer available because they were disabled.  Kind of like how people remove docks from the UI and then wonder why they're not there anymore.  I'd recommend thoroughly going through all of the settings in OBS.  Also, before ever changing any settings throughout the program be sure to know the full implications of what the change will bring.

**Comment by Xaymar** [comment]
4 days have passed, and therefore I'm closing this.
