### ISSUE TITLE
GTX 1050 ti setting

### ISSUE THREAD

**Issue by massatt212** [Xaymar/obs-StreamFX#317]
dont mean to ask for a setting guide here, but anytime i join discord it kicks me out of the channel.
i want to know if using your Nvenc ffmpeg is better than new nvenc on a gtx 1050 ti

And if i can get better quality from yours, do you have a quick setup guide i can follow for best output my gpu can handle.

**Comment by skeletonbow** [comment]
Discord tip:  The #rules channel on the Discord server explains the rules and server operation including how to get full access to channels of interest.  Be sure to read it carefully.

**Comment by Xaymar** [comment]
You will be automatically removed from the Discord if after 10 minutes you still not meet the most basic verification setting. This is in order to combat spam and lurkers who only join to artificially inflate member count. None of the roles are required to see the announcements, but you will have to agree to the rules on the Discord. 

[Also I'm pretty sure I had a template that wasn't supposed to just be deleted.](https://github.com/Xaymar/obs-StreamFX/issues/new?template=help.md)
