### ISSUE TITLE
OBS v24 + StreamFX?

### ISSUE THREAD

**Issue by ochen1** [Xaymar/obs-StreamFX#332]
### Description

Recently, I discovered a plugin that only works on OBS version 24.
Is there a precompiled version of StreamFX for Linux that works with v24.0.6?
I've tried some of the releases releases dating back to around March/April 2020 (when OBS v24 was released), but they caused segmentation errors and didn't work.

Could someone point me to a precompiled / source code / release that works with OBS?

Any help would be greatly appreciated!

### System Information

- Software Version: OBS 24.0.6 (Linux)
- Operating System: Linux Mint (XFCE)
- Kernel Version:  5.4.0-47-generic #51-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
- CPU: Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz
- GPU: Integrated
- RAM: 16GB

**Comment by Xaymar** [comment]
Older OBS Studio versions are unsupported due to the number of bugs in them that I had to work around, and sometimes even mess around in memory for. All the legacy code that does this messing around has been removed in the current versions of the plugin.

There are no precompiled versions of StreamFX for Linux for ancient OBS Studio versions.

**Comment by ochen1** [comment]
I get it now. Looks like I'll just have to bug the other plugin dev.

Thank you!
