### ISSUE TITLE
obs_module_load symbol missing -> StreamFX not loaded

### ISSUE THREAD

**Issue by asterbini** [Xaymar/obs-StreamFX#372]
### Description
I am trying to compile obs-StreamFX for Linux.
All goes well but the StreamFX.so resulting library does not load because it does not contain the obs_module_load symbol

I remember that the previous version worked fine

```
[root@HEX build]# nm -gDC StreamFX.so  | grep load
                 U gs_load_indexbuffer
                 U gs_load_texture
                 U gs_load_vertexbuffer
                 U obs_module_load_locale
```

### System Information

- Software Version: OBS 26.0.2   obs-StreamFX as of November 2nd 2020
- Operating System: Fedora 32
- Kernel Version: 5.8.15 Linux
- CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
- GPU: NVIDIA Corporation GM204M [GeForce GTX 970M] (rev a1)
- RAM: 16GB

**Comment by Xaymar** [comment]
Did you follow the build guide? https://github.com/Xaymar/obs-StreamFX/wiki/Building-From-Source

**Comment by asterbini** [comment]
Yes, to be sure I re-built it with cmake and ninja (earlier I had used ccmake) as described there.
Still the module is'nt loaded

`
01:19:15 PM.213: Required module function 'obs_module_load' in module '/home/andrea/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so' not found, loading of module failed
01:19:15 PM.213: Failed to load module file '/home/andrea/.config/obs-studio/plugins/StreamFX/bin/64bit/StreamFX.so': -3`

**Comment by asterbini** [comment]
SUCCESS!!
I have switched to the 0.9.1 branch and the module compiled fine!

**Comment by Xaymar** [comment]
What build steps did you use to build master? It doesn't seem to be a problem on CI.

**Comment by asterbini** [comment]
Possibly a standalone/plugin/xxx configuration option missing?

**Comment by Xaymar** [comment]
Identified the problem. In `CMakeLists.txt` I apply compiler specific overrides, where I accidentally copied the `-fvisibility=hidden` flag from the VoiceFX project, which needed to only export certain symbols in order to stay true to the specification and pass verification.

Reason for this is that the `MODULE_EXPORT` (and `EXPORT` macro defined by libOBS does not tag the function as visible, which means that all functions are hidden - except a few statically linked in symbols by the compiler that have to be visible.

**Comment by Xaymar** [comment]
Hi @asterbini, have you tried the patch in #375?

**Comment by asterbini** [comment]
Yes, it works!!!
Thanks
