### ISSUE TITLE
3 Antivirus engines detect StreamFX as malicious

### ISSUE THREAD

**Issue by svpn** [Xaymar/obs-StreamFX#374]
https://www.virustotal.com/gui/file/0a18cc047d5a50eae24928c9fc335df2c9b2e1dcf32e88a49906fc4fc52d0f1c/detection

**Comment by Xaymar** [comment]
**TL;DR: False positives due to behavior match.**

These are false positives due to a behavior "match" in certain AV engines, where the AV engines checks for what is imported from system libraries and makes an incorrect call on what it is. As you can see, 69 other engines correctly identify it as an installer, instead of treating installer behavior like a Virus.

Additionally, please do not remove the template or I will permanently prevent you from creating issues.
