### ISSUE TITLE
No more Windows archive download?

### ISSUE THREAD

**Issue by ImportTaste** [Xaymar/obs-StreamFX#536]
I typically use a script to keep this plugin up to date, pulling API data from GitHub. However, it seems that you're only providing an installer solution now. I use the portable version of OBS, so this is very inconvenient for me.

I did notice that it does get made in the download artifacts, but it's an archive within an archive and is going to be a gigantic pain in the ass to figure out how to incorporate into my script.

Could you provide a windows archive download again?

**Comment by Xaymar** [comment]
**Please don't delete the template when submitting features, issues or pull requests!**

**Comment by ImportTaste** [comment]
Oh for fuck sake.

**Comment by Xaymar** [comment]
This was announced on 2021-03-27. Archive releases have been discontinued until further notice due to increased support traffic which always came down to the user not reading the instructions and installing it correctly. In the future, the Windows Installer will offer a portable installation option, but this has not made it into the 0.10 release.
