### ISSUE TITLE
'Manual install' zip for 0.10 on Windows, for additional portable instances not at the standard install path

### ISSUE THREAD

**Issue by PoliteTimesplitter** [Xaymar/obs-StreamFX#538]
### Description
I have two installs of OBS Studio, both of them portable, one at 'program files\obs-studio' and the other at 'program files\obs-studio SECONDARY' that I keep for different purposes and sometimes run in tandem. Both use StreamFX. Downloading the 0.10 windows installer has gotten my main one, the first path, updated fine, but I can't seem to get it to install to Secondary, which is still on 0.9.3, the first version of SFX I installed.

The downloads for 0.9.3 include .zip and .7z with the data and obs-plugins folders for a manual install, which is probably how I got 0.9.3 installed on the secondary one in the first place as Secondary doesn't have an uninstaller. These options aren't present for 0.10 on Windows, just Ubuntu. Compiling it myself is something absolutely above my skill level, I am a dunce.

### Checklist

- [X] I am willing to pay someone to implement this feature [patreon contribution].
- [ ] This feature absolutely can't be done with already existing features.

**Comment by skeletonbow** [comment]
A decision was made by the project to discontinue the ZIP file downloads due to too many bad tutorials out there encouraging inexperienced users to download them and end up unable to follow instructions properly to install them, leading to droves of people coming looking for support.  It's an inefficient solution ultimately.  So it was decided to discontinue the ZIP file to force people to always use the EXE installer which does the right thing, and if there are any problems with that to file bug reports so the installer can be fixed, or new features added for special cases.

Unfortunately the feature for installing into portable installs isn't present in the current 0.10 release but will be added to a future update.  Until then people using portable installs or other special cases will have to either keep using the previous stable release of 0.9.3, or to copy the files over from one installation installed from the EXE file to another, or to extract the files from the EXE file manually (using installer tools potentially), or to compile from source.  I believe those are the only options for 0.10 currently.

When the installer is updated in the future to handle portable installs it should more or less handle the common cases, and if anyone else has a special case they used to use the ZIP files for, they can always file a request indicating their use case to see if it can be accommodated in the future.

The end result is a much better end user experience from the EXE installer, a dramatic reduction in the number of inbound support requests from inexperienced users installing the wrong things in the wrong place, and an increase in productivity for the project.

HTH

**Comment by PoliteTimesplitter** [comment]
Thank you for the response, that makes a lot of sense and I appreciate why that decision was made. I'll keep my eyes peeled for future updates and look forward to seeing it when it happens. Cheers!
