### ISSUE TITLE
shader filter - text source (GDI) - ascii in text field

### ISSUE THREAD

**Issue by mpek** [Xaymar/obs-StreamFX#609]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.0

### StreamFX Version

0.10.1

### OBS Studio Log

https://obsproject.com/logs/Fp5Fh8v1RAaGxhfL

### OBS Studio Crash Log

[Crash 2021-08-10 12-16-21.txt](https://github.com/Xaymar/obs-StreamFX/files/6960895/Crash.2021-08-10.12-16-21.txt)

### Current Behavior

I changed settings and suddenly obs freezed and crashed stopped to stream and closed.

### Expected Behavior

I added shader filter to a Text source (GDI) and has ascii signs in the text field that i wanted to adjust with the shader filter

### Steps to Reproduce the Bug

I added shader filter to a Text source (GDI) and has ascii signs in the text field that i wanted to adjust with the shader filter

**Comment by Xaymar** [comment]
The crash location is not within StreamFX, but within OBS Studio.

**Comment by Xaymar** [comment]
**This appears to be a bug upstream in OBS Studio!**  
The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the de-facto leader of the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.
