### ISSUE TITLE
Option to stream / record with AV1

### ISSUE THREAD

**Issue by Felixkruemel** [Xaymar/obs-StreamFX#610]
### Explain the Feature/Enhancement

It woudl be great to have an option to encode with libaom as ffmpeg plugin as YouTube already supports it and it got extremely fast in recent months [https://openbenchmarking.org/test/pts/aom-av1&eval=03b54073fbfc5af0aa5974f95d4d31daeba196da#metrics](https://openbenchmarking.org/test/pts/aom-av1&eval=03b54073fbfc5af0aa5974f95d4d31daeba196da#metrics) and compared to (by now ancient) x264 it offers a way better quality for the same bitrate.

### What makes this feature/enhancement useful for StreamFX and its users?

You already had an plugin for it available, but discarded it: https://github.com/Xaymar/obs-enc-aomedia-av1
Would be great to have an all-in-one plugin containing it.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
At the moment, there is no home computer that can encode AV1 anywhere near real time.

**Comment by Felixkruemel** [comment]
@Xaymar Where do you have this information from?

It's true that non-rt mode encoding is way too slow, but even an midrange Ryzen 5 gets more than 100fps on realtime Mode with cpu-used=9

**Comment by Xaymar** [comment]
The information is from me, I've tested a variety of AV1 encoders over the years, retesting every time there was something to test. The closest to real-time with actually useful output was [svt-av1](https://gitlab.com/AOMediaCodec/SVT-AV1) on a AMD Ryzen 5950X at 1080p60, averaging 59.45 fps on the fastest setting. libaom in any useful setting barely ever managed

If "real-time" mode has improved over the last few months, and still produces useful results, I will have to re-test. At the time though, "real-time" produced results worse than or equal to x264 slow in the content that StreamFX is used for.

**Comment by Xaymar** [comment]
I've looked at the footage that they are testing with, and it is nothing impressive to encode. Using that as a speed metric most likely does not reflect any real world performance, at all, ever.

**Comment by Xaymar** [comment]
Got AOM AV1 built myself on Windows, and at least in performance they have made massive leaps since my last test. Though in quality it is behind libsvt-av1's fastest preset, in performance it is ahead - way ahead, as it scales much better with resolution and framerate than libsvt-av1 does. As for the configuration options, `--rt --cpu-used=7` is about the best in terms of quality, while only being ~15fps slower than `--rt --cpu-used=9`.

Is it worth it to include? Perhaps. It should definitely be possible to record with AOM AV1, if you have the hardware for it.

**Comment by Felixkruemel** [comment]
@Xaymar 
What you are saying with SVT btw. is totally right.
SVT right now is beating AOM in terms of speed/performance in non-rt-mode scenarios down to preset 5. 

So basically use AOM for Realtime encoding and SVT for production encoding. The AOM encoder focused a lot on RT performance in the last months, not in non-rt performance since SVT switched to beeing the official production encoder for that.


Would be amazing to have support for it :)

**Comment by Xaymar** [comment]
> How much fps did you get with your 5950X on --cpu-used=7?

At 1080p60 with a game in the background, --cpu-used=9 nets me about 84fps, while --cpu-used=7 ends up at just above 53fps. 

> Also just for me, how do you include custom ffmpeg encoders via a plugin? Maybe I could help getting this done here.

If the encoder is part of the FFmpeg binary available on the system and/or shipped with OBS Studio, then all you have to do is write and maintain a front-end for it.

**Comment by Felixkruemel** [comment]
> At 1080p60 with a game in the background, --cpu-used=9 nets me about 84fps, while --cpu-used=7 ends up at just above 53fps.
Mhmm okay, that sounds reasonable. Should be mostly single-threaded I guess, at least that's the case for my tests with non-rt so the 5950X isn't that much better.
> If the encoder is part of the FFmpeg binary available on the system and/or shipped with OBS Studio, then all you have to do is write and maintain a front-end for it.
Problem is that it is not shipped with OBS Studio and you cannot require from someone that you put a custom ffmpeg in PATH. Is there a way to ship a custom ffmpeg with a plugin?

**Comment by Xaymar** [comment]
> Problem is that it is not shipped with OBS Studio and you cannot require from someone that you put a custom ffmpeg in PATH. Is there a way to ship a custom ffmpeg with a plugin?

Unfortunately not, unless you want to deal with dependency hell on a modern Operating System. We don't want to deal with FFmpeg anyway if we can just directly call into the AOM AV1 encoder, saves a lot of CPU resources if we can directly access it.

**Comment by Xaymar** [comment]
I got AOM AV1 to build [automatically on Windows](https://github.com/Xaymar/aom/releases), so it should be possible to integrate the encoder directly. The highest FPS I've seen with MSVC generated binaries was 109.4 fps, which is much faster than x264 and x265 at comparable quality. Impressive optimization work.

**Comment by Xaymar** [comment]
We're looking for volunteer participants in a test run of the AOM AV1 encoder! The goal is to figure out hardware requirements for realtime 1080p60 4:2:0 encoding. At the moment the encoder is only available on Windows and Linux.

More Information: https://discord.com/channels/736503051824922685/736555882783047760/881170009521524767

**Comment by Nofew** [comment]
You pasted the URL for a channel, but not an invite. I can't get on the server to help you. Could'ya post an invite URL?

**Comment by Xaymar** [comment]
> You pasted the URL for a channel, but not an invite. I can't get on the server to help you. Could'ya post an invite URL?

The Discord is linked on the main page of the repo, but anyway: https://s.xaymar.com/streamfx-dc

**Comment by Nofew** [comment]
Thank you again!

**Comment by Xaymar** [comment]
There's some good news, and some bad news, but we'll start with the good news.

Through the recent testing efforts, it's become somewhat clear what the minimum requirements will end up being for 1080p60 4:2:0 at the fastest possible settings. You will most likely require an AMD Ryzen 5600X with high speed memory and good timings to pull it off without dropping too many frames. This will most likely consume the entirety of the PC just for encoding, so it's only an option for multi-PC streaming right now. Hopefully this can improve drastically.

As for the bad news, it turns out integrating it into OBS resulted in nearly 30% of performance lost somewhere. I've profiled the OBS integration, and the only obvious culprit appears to be `aom_codec_encode`, which in more than 1% of calls ended up taking more than the ideal frame time to encode. I'm hoping this improves in the future, but right now it appears that the hardware requirements for Gaming plus Streaming are high-end to enthusiast level, even with the fastest settings.

On the plus side, even at the fastest settings, AV1 doesn't turn to a blocky mess _yet_, like H.264 does. I'd still very much prefer AV1 over H.264 in low bitrate situations.

**Comment by Xaymar** [comment]
The AV1 Encoder based on AOM will be available in v0.11 as **Experimental** (if you don't know what that means, the wiki has the answer if you look at it enough). Closing this in favor of the PR.

**Comment by Felixkruemel** [comment]
Just asking again, is there a way to make it possible to stream using AV1 @Xaymar ?
I know that Twitch and YT don't support it as input (yet), but you can enter a custom URL and for that I really would love to use AV1 with SVT.

**Comment by Xaymar** [comment]
> @Felixkruemel Just asking again, is there a way to make it possible to stream using AV1 @Xaymar ?

StreamFX is not the one limiting your from doing this.
