### ISSUE TITLE
Replace Me Or Have Your Request Closed

### ISSUE THREAD

**Issue by DigibitDK** [Xaymar/obs-StreamFX#620]
### Explain the Feature/Enhancement

Being able to stream in h.265/HEVC (Using SRT-protocol)

### What makes this feature/enhancement useful for StreamFX and its users?

I'm desperately trying to find a way to stream using h.265. I have the latest test-version of StreamFX, but still no option to do so.

I have seen screen-shots of people having 'AMD h.265', but well, I have an Intel CPU and a GTX 1060 card, so that might be the reason why I dont have any h.265-option. Is it only limited to AMD-users?

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

### Any additional Information we need to know?

 I have an Intel CPU and a GTX 1060 card

**Comment by Xaymar** [comment]
**This appears to be a bug upstream in OBS Studio!**  
The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.

**Comment by Xaymar** [comment]
As StreamFX is only a plugin to libOBS, it is not able to modify the UI you use to control libOBS. OBS Studio is preventing you from streaming with anything but H.264 at the moment.

**Comment by DigibitDK** [comment]
That's sad :( But thanks guys! Great project!

**Comment by DigibitDK** [comment]
PS: Let me know, if there is any workarounds to do so, behind the UI or something :)

**Comment by Seaward233** [comment]
> PS: Let me know, if there is any workarounds to do so, behind the UI or something :)
You can use the record menu to stream in hevc
![photo_2021-09-29_23-25-20](https://user-images.githubusercontent.com/35931149/135299899-267eee8b-992e-4c27-adda-1047e12cc24f.jpg)
