### ISSUE TITLE
Replace Me Or Have Your Request Closed

### ISSUE THREAD

**Issue by SanyaSenju** [Xaymar/obs-StreamFX#629]
### Explain the Feature/Enhancement

Add whitelist for apps to display the game correctly or capture this game from obs itself

### What makes this feature/enhancement useful for StreamFX and its users?

Some applications (eg Steam) are captured and changed to this category.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
**This appears to be a bug upstream in OBS Studio!**  
The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.
