### ISSUE TITLE
Allow Video Filters to be added to Source Mirrored video sources

### ISSUE THREAD

**Issue by jefuslives** [Xaymar/obs-StreamFX#741]
### Explain the Feature/Enhancement

Currently, only Audio Filters and Effects Filters can be added to a Source Mirror source, even if the mirrored source can usually have Video Filters added to it.

### What makes this feature/enhancement useful for StreamFX and its users?

Availability of video filters which are currently inaccessible thru a mirrored source, such ad Background Removal, and Video Delay, as well as any number of plugin-based filters that normally appear under the "Video Filters" heading.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by Xaymar** [comment]
This is not something StreamFX can do, it would be up to OBS Studio to allow this.

**Comment by Xaymar** [comment]
**This appears to be a bug upstream in OBS Studio!**  
The bug or problem you reported appears to originate from OBS Studio. Unfortunately, due to past disagreements with the OBS Project team about how the project is run, I have been asked to no longer submit bugs or fixes to OBS Studio or any of its direct projects. I will abide by this agreement, until it is lifted or other means force me to no longer abide by this agreement.

**Comment by Xaymar** [comment]
Since it appears you are unaware of the difference between Effect and Video filters:

- Video filters happen in "software" - often on the CPU - and require that the GPU frame is first downloaded to the CPU.
- Effect filters happen in "hardware" on the same GPU, thus they have only their effect cost attached.

That means that your feature request is misplaced, as it would be up to whoever implemented those filters to add a version that works in the Effect filters list.
