### ISSUE TITLE
Corner Pin applies to whole source, not cropped and visible one

### ISSUE THREAD

**Issue by odecroupette** [Xaymar/obs-StreamFX#758]
### Explain the Feature/Enhancement

when you apply the corner pin 3d transform, the transform uses the whole picture from the source. It could be usuefull but many times you crop the size of your source, so the 3d transform apply to expectedly invisible content. So the behavior is different from many video editing software, but alos makes it more complicated to get what you want.

### What makes this feature/enhancement useful for StreamFX and its users?

I would rather transform the visible image (cropped one) and possibly add a checkboxw if you want tyo apply to whole source image for that particular use case.

### Checklist

- [ ] I am offering a monetary bounty/reward for the implementation of this Feature/Enhancement.
- [X] There is no other way to currently do this in StreamFX or OBS Studio.

**Comment by odecroupette** [comment]
Also, i applied it in my scnene containing a nested scene source (with my camera), and the effect is applied to my source scene too.

**Comment by skeletonbow** [comment]
How are you performing the crop operation, by using the OBS Crop/Pad filter, or by using the crop feature in the transform dialogue?  If you're using the transform dialogue crop then it is working as expected as that occurs AFTER all filters have been applied.  If you're using the Crop/Pad filter, it should be placed BEFORE the StreamFX filter in order to work correctly.

**Comment by odecroupette** [comment]
i'm using the standard ALT cropping method in OBS.

**Comment by skeletonbow** [comment]
> i'm using the standard ALT cropping method in OBS. so i can not order any filter as i have only the 3d tarnsform

That's why it isn't working, that is the transform dialog crop which occurs only after all filters have been applied, so you are transforming first and then cropping.  In order for what you want to work you have to undo your current crop, then add a Crop/Pad filter before the 3D Transform filter so that it crops first and then does the Corner Pin.

The order filters get applied in is important to correct operation.

**Comment by Xaymar** [comment]
Not a bug, please watch one of many master guides for OBS Studio.

**Comment by Xaymar** [comment]
**Please use the [Discord](https://s.xaymar.com/streamfx-dc) server for support!**
We've decided to move all support to the Discord, as users frequently ignore any requests for additional data, or failed to provided even the minimum data required to provide proper help. Once you've joined, look at the `support-hub` channel for further instructions, and make sure you follow the `rules`.
