### ISSUE TITLE
Some Shaders breaking Dynamic Mask

### ISSUE THREAD

**Issue by spectangulation** [Xaymar/obs-StreamFX#770]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

this issue doesn't appear on logs

### OBS Studio Crash Log

no crashes

### Current Behavior

When I use dynamic mask, keying green out of alpha, some shaders causes the keyed out areas to appear black and opaque. 

### Expected Behavior

the expectation is that keyed out areas in Dynamic Mask remain keyed regardless of the applied shader.

### Steps to Reproduce the Bug

1. apply dynamic mask
2. key out colour
3. apply affecting shader

### Any additional Information we need to know?

these shaders are breaking Dynamic Mask:

- CRT curvature
- pixelization
- hexagonize
- smaa

**Comment by Xaymar** [comment]
#### Rejected: Not a bug.
The Shader filter itself supports Alpha/Transparency just fine, so some examples not having support for it is not a bug. There isn't even a way for SMAA to have Alpha support, since SMAA itself does not have Alpha support. Similar situations with the other shaders - it would change their entire meaning.
