### ISSUE TITLE
Stream won't start after newest OBS Update. Potentially StreamFX related

### ISSUE THREAD

**Issue by zidake** [Xaymar/obs-StreamFX#780]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.2

### StreamFX Version

0.11.1a1

### OBS Studio Log

https://obsproject.com/logs/HFg8BVeQtS8s68X5

### Current Behavior

Since the last OBS Update (27.2) I can't start my stream anymore. When I press 'Start Stream' I immediately get a notifaction that I should check my logfiles.
After I talked to someone in the obs discord he suggested I should open an issue on your github. This was found in my log and could cause my issue:

[StreamFX] Unexpected exception in function '_create': Invalid argument.

### Expected Behavior

Stream should start

### Steps to Reproduce the Bug

Just clicking 'Start Streaming'

**Comment by HunterAP23** [comment]
First, you might want to update from the 11.1 Alpha to the Beta release, some more ffmpeg fixes were applied there
Second, the log you posted doesn't show any attempt at starting a stream, so we can't really rule out anything from this log. After updating to the beta release, try starting a stream and grabbing that current log and posting it here

Another thing you can post is a screenshot of the encoder settings you're using

**Comment by zidake** [comment]
It works now with the beta release. Thanks.

**Comment by Xaymar** [comment]
#### Rejected: User Error
The error is caused by you updating OBS Studio, but not adjusting your FFmpeg encoder settings to match the updated FFmpeg version. StreamFX is not providing the encoder itself, just the user interface to it, and as such will try to not mess with the settings you tell it to use at all. See previously opened issues about the exact same thing.
