### ISSUE TITLE
[0.11.1] Deleting "Shader" Filter will crash in win10 1809 LTSC.

### ISSUE THREAD

**Issue by iesvme** [Xaymar/obs-StreamFX#787]
### Operating System

(Other)

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

https://obsproject.com/logs/Klx0WAzm9Vcnt0ye

### OBS Studio Crash Log

https://obsproject.com/logs/1FdhGKI7b21Y-KWX

### Current Behavior

Deleting "Shader" Filter will crash in win10 1809 LTSC.

### Expected Behavior

Deleting "Shader" Filter won't crash.

### Steps to Reproduce the Bug

1. add Text source
2. add Shader filter
3. delete Shader filter
4. crash

**Comment by Xaymar** [comment]
#### Rejected: Caused by other Software
Based on the data reported, the problem is caused by third-party Software (or Plugins to Software), and as such can't (and won't) be supported here. Please seek the proper help channels for the problem you encountered.

Additionally, the [System Requirements](https://github.com/Xaymar/obs-StreamFX/wiki/System-Requirements) are requirements, not guidelines. Windows 10 before 1903 is unsupported completely.
