### ISSUE TITLE
Cant find Upscaling oder Virtual Greenscreen filter on my filterlist

### ISSUE THREAD

**Issue by ping-mee** [Xaymar/obs-StreamFX#788]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

https://obsproject.com/logs/ZSrocPPiMeiW65U5

### Current Behavior

The virtual greenscreen filter and the upscaling filter are not showing up in my filter list. Other filters from StreamFX are showing up like Blur

### Expected Behavior

i think thats kinda self explaining. I want to use the upscaling and virtual greenscreen filter.

### Steps to Reproduce the Bug

I dont know how to reproduce this bug. I reinstalled StreamFX several times with deifferent version and nothing happened.

**Comment by ping-mee** [comment]
BTW the file virtual-greenscreen.effect exsists in my obs plugins data folder

**Comment by Xaymar** [comment]
#### Rejected: User Error
The [manual](https://github.com/Xaymar/obs-StreamFX/wiki) explains clearly what is necessary to get these features to appear. In the future, please do not abuse the issue tracker for support, otherwise you will be permanently blocked from interacting with it. Instead [join the official Discord](https://discord.com/channels/736503051824922685/772562535761051728/860151349681192976) for support, which is also where the "Help & Support" link goes to in the StreamFX menu.
