### ISSUE TITLE
SSP Source Breaks shaderfilters.

### ISSUE THREAD

**Issue by jdudetv** [Xaymar/obs-StreamFX#792]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

(Other)

### StreamFX Version

0.11.0c1

### OBS Studio Log

https://obsproject.com/logs/sRYB4n6HCRCTV_Yr

### Current Behavior

If an [SSP Source](https://github.com/summershrimp/obs-ssp/releases) is initialised any streamfx filters fail to load. They appear in the dropdown and you can add it but are fully unresponsive and dont effect anything visually. Worked previously on version 0.10.x of StreamFX

### Expected Behavior

Filters work as intended.

### Steps to Reproduce the Bug

Install the SSP plugin. Connect to a SSP device. add a streamfx filter anywhere in OBS. 

### Any additional Information we need to know?

Using the latest version of OBS (27.2.3) and latest version of StreamFX 0.11.1

**Comment by Xaymar** [comment]
#### Rejected: Caused by other Software
Based on the data reported, the problem is caused by third-party Software (or Plugins to Software), and as such can't (and won't) be supported here. Please seek the proper help channels for the problem you encountered.

StreamFX relies entirely on the OBS API and Windows API functionality working as intended. If installing a third party plugin breaks this expectation for some reason, the problem lies with the third party plugin. See [here](https://github.com/Xaymar/obs-StreamFX/blob/master/source/gfx/shader/gfx-shader.cpp#L81) and [here](https://github.com/Xaymar/obs-StreamFX/blob/master/source/gfx/shader/gfx-shader.cpp#L81) for the lines that it somehow affects.

As it seems that their plugin either hooks into, replaces or modifies the C++ API, their plugin should be used with extreme caution and handled with extreme suspicion of spyware/malware behavior. No plugin should have any reason to mess with the Microsoft provided C++ API at all.

**Comment by Xaymar** [comment]
Looking at it further, it is breaking a lot more than just those two locations. Why it does this is unknown to me, and I'll assume incompetence before I assume evil intentions for now.
