### ISSUE TITLE
Source Mirror - Video Delay (Async)

### ISSUE THREAD

**Issue by sweetngx** [Xaymar/obs-StreamFX#796]
### Operating System

Windows 10 1903 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

None

### Current Behavior

None

### Expected Behavior

None

### Steps to Reproduce the Bug

I'm trying to add a Video Delay (Async) filter to the Source Mirror but nothing happens, I don't know if it's a bug or intentional, But I want to add a delay to the mirror, is it possible?

**Comment by Xaymar** [comment]
#### Rejected: Caused by other Software
Based on the data reported, the problem is caused by third-party Software (or Plugins to Software), and as such can't (and won't) be supported here. Please seek the proper help channels for the problem you encountered.

Video Delay (Async) is incorrectly available on an audio-only source. Please report this to the correct place.
