### ISSUE TITLE
Crash when removing a Shader filter while in use

### ISSUE THREAD

**Issue by adammw** [Xaymar/obs-StreamFX#802]
### Operating System

MacOS 10.15 and higher

### OBS Studio Version?

27.1

### StreamFX Version

0.11.0c1

### OBS Studio Log

https://gist.github.com/adammw/8fb3936d9ca246e4886f022352050ed6

### OBS Studio Crash Log

https://gist.github.com/adammw/d6abdb95b7f0d4f743dec15d2108da5a

### Current Behavior

Crash when removing a Shader filter while in use 

### Expected Behavior

The filter to be removed

### Steps to Reproduce the Bug

Add a shader filter to a video source, then attempt to remove it.

**Comment by Xaymar** [comment]
#### Rejected: Caused by other Software
Based on the data reported, the problem is caused by third-party Software (or Plugins to Software), and as such can't (and won't) be supported here. According to the provided crash log, the crash is caused by code interfacing with Qt in the OBS Studio project. Please seek the proper help channels for the problem you encountered.
